---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "/collision_detect"
  gz_topic_name: "/model/ebot/link/ebot_base/sensor/collision_sensor/contact"
  ros_type_name: "gazebo_msgs/msg/ContactsState"
  gz_type_name: "gz.msgs.Contacts"
  direction: GZ_TO_ROS
  
- ros_topic_name: "/ebot/cmd_vel"
  gz_topic_name: "/model/ebot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "/ebot/odometry"
  gz_topic_name: "/model/ebot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

- ros_topic_name: "/ebot/scan"
  gz_topic_name: "/model/ebot/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS  

- ros_topic_name: "/${name}/scan"
  gz_topic_name: "/model/ebot/${name}/scan"
  ros_type_name: "sensor_msgs/msg/Range"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS  
  
- ros_topic_name: "/imu"
  gz_topic_name: "/model/ebot/imu_sensor/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
  
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/eyantra_world/model/ebot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
  
- ros_topic_name: "/tf"
  gz_topic_name: "/model/ebot/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  
- ros_topic_name: "/tf_static"
  gz_topic_name: "/model/ebot/pose_static"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

